### ISSUE TITLE
Chrome&Safari vs Firefox differences

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testausserveri.fi#38]
Chrome and Safari look almost the same:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/46541386/167259185-e16367b5-70df-4149-ae8c-c4cf388053ba.png">

, but Firefox looks a bit funky:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/46541386/167259208-1422900f-e698-40ff-a43c-f082439c9532.png">

Unsure why, but it seems visually that the content starting from gradient heading is too high up. One fix of course would be to check if it's Firefox and apply browser-specific fixes, but I'm not sure whether that's ideal solution.

**Comment by ahnl** [comment]
I think I have identified the cause being the negative margin-bottom on .hero class of DiscordLive component.

https://github.com/Testausserveri/testausserveri.fi/blob/coal/components/DiscordLive/DiscordLive.module.css#L87

Feel free to investigate further and possibly find a solution to this problem.

**Comment by Eldemarkki** [comment]
This is caused because Firefox doesn't support the `zoom` CSS property: https://caniuse.com/css-zoom. If I disable the `zoom` property on Chrome, it looks the same as it does on Firefox:

Chrome (with `zoom` disabled):
![image](https://user-images.githubusercontent.com/38920928/167895669-79274bf7-3c99-4a96-a2f3-97b462364166.png)

Firefox:
![image](https://user-images.githubusercontent.com/38920928/167895791-ad70ac55-0f64-484d-a263-2d1d4a8a2dba.png)

**Comment by ahnl** [comment]
Interesting, thank you @Eldemarkki for this finding!
